import Head from 'next/head'
import LandingPage from '@/components/pages/landing/LandingPage'
import BaseLayout from '@/components/layout/BaseLayout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <LandingPage />
      </BaseLayout>
    </>
  )
}
